const app=document.querySelector('#app');
// When the host opens the table locally, share the reachable LAN address rather than localhost.
const shareOrigin=location.hostname==='localhost'?'http://192.168.1.128:3100':location.origin;
let state={screen:'home',mode:'individual',max:4,name:'',avatar:'🦊',room:null,player:null,game:null,selected:null};
const avatars=['🦊','🐼','🐯','🦉','🐸','🦁'];
function esc(s){return String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));}
function toast(t){document.querySelector('.toast')?.remove();let d=document.createElement('div');d.className='toast';d.textContent=t;document.body.append(d);setTimeout(()=>d.remove(),2600)}
async function api(url,data){let r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}),j=await r.json();if(!r.ok)throw Error(j.error);return j}
function home(){app.innerHTML=`<main class="wood"><section class="hero"><div class="eyebrow">A MODERN TABLETOP CLASSIC</div><h1 class="title">SEQUENCE</h1><p class="subtitle">Classic Strategy. New Digital Experience.</p><div class="hero-board"></div><div class="actions"><button class="btn" onclick="setup()">PLAY</button><button class="btn dark" onclick="howto()">HOW TO PLAY</button><button class="btn dark" onclick="join()">JOIN GAME</button><button class="btn" onclick="setup()">CREATE GAME</button></div></section></main>`}
function setup(){state.screen='setup';app.innerHTML=`<main class="wood"><section class="setup panel"><div class="eyebrow">SET THE TABLE</div><h2 class="subtitle">Choose your match</h2><div class="choices"><button class="choice ${state.mode==='individual'?'selected':''}" onclick="state.mode='individual';setup()">INDIVIDUAL</button><button class="choice ${state.mode==='team'?'selected':''}" onclick="state.mode='team';setup()">TEAM PLAY</button></div><div class="choices">${[2,3,4].map(n=>`<button class="choice ${state.max===n?'selected':''}" onclick="state.max=${n};setup()">${n} PLAYERS${n===4?'<small><br>RECOMMENDED</small>':''}</button>`).join('')}</div><div class="form-row"><input id="name" placeholder="Your name" value="${esc(state.name)}"><button class="btn" onclick="createGame()">CREATE ROOM</button></div><div class="avatar-picker">${avatars.map(a=>`<span onclick="state.avatar='${a}';setup()" style="opacity:${a===state.avatar?1:.35}">${a}</span>`).join('')}</div><button class="btn dark" onclick="home()">BACK</button></section></main>`}
async function createGame(){state.name=document.querySelector('#name').value.trim()||'Host';try{let x=await api('/api/create',{mode:state.mode,max:state.max,name:state.name,avatar:state.avatar});state.room=x.room;state.player=x.player;lobby();connect()}catch(e){toast(e.message)}}
function join(){app.innerHTML=`<main class="wood"><section class="setup panel"><h2 class="subtitle">Join a game room</h2><div class="form-row"><input id="code" placeholder="ROOM CODE"><input id="name" placeholder="Your name"><button class="btn" onclick="joinGame()">JOIN TABLE</button></div><div class="avatar-picker">${avatars.map(a=>`<span onclick="state.avatar='${a}';join()" style="opacity:${a===state.avatar?1:.35}">${a}</span>`).join('')}</div><button class="btn dark" onclick="home()">BACK</button></section></main>`}
async function joinGame(){try{let x=await api('/api/join',{room:document.querySelector('#code').value,name:document.querySelector('#name').value||'Guest',avatar:state.avatar});state.room=x.room;state.player=x.player;lobby();connect()}catch(e){toast(e.message)}}
function connect(){state.es?.close();state.es=new EventSource(`/events?player=${state.player}`);state.es.addEventListener('state',e=>{state.game=JSON.parse(e.data); if(state.game.started)game();else lobby()})}
function lobby(){let g=state.game||{code:state.room,players:[],max:state.max,host:state.player};app.innerHTML=`<main class="wood"><section class="lobby panel"><div class="eyebrow">SEQUENCE TABLE</div><div class="lobby-code">${g.code}</div><p class="note">Share this room code, or copy the invite link.</p><div class="actions"><button class="btn dark" onclick="navigator.clipboard.writeText(shareOrigin+'/?room=${g.code}');toast('Invite link copied')">COPY INVITE LINK</button><button class="btn dark" onclick="navigator.clipboard.writeText('${g.code}');toast('Room code copied')">COPY CODE</button>${g.host===state.player?'<button class="btn" onclick="start()">START GAME</button>':''}</div><div class="seats">${Array.from({length:g.max},(_,i)=>{let p=g.players.find(q=>q.seat===i);return `<div class="seat" style="--c:${p?.color||'#6c6c6c'}">${p?`${p.avatar||'🦊'} <strong>${esc(p.name)}</strong> — Ready${p.id===g.host?' · HOST':''}`:`Seat ${i+1} — Waiting for player…`}</div>`}).join('')}</div><button class="btn dark" onclick="home()">LEAVE TABLE</button></section></main>`}
async function start(){try{await api('/api/start',{room:state.room,player:state.player})}catch(e){toast(e.message)}}
function cardDead(c,g){return !c.jack&&!g.board.some(x=>!x.corner&&!x.chip&&x.rank===c.rank&&x.suit===c.suit)}
function game(){let g=state.game,me=g.me;if(!me)return;let mine=g.turn===me.id;let selected=me.hand.find(c=>c.id===state.selected);let legal=c=>{if(!selected||!mine)return false;if(selected.eye==='two')return !c.chip&&!c.corner;if(selected.eye==='one')return !!c.chip&&!c.locked.length&&c.chip!==me.id;return !c.chip&&!c.corner&&c.rank===selected.rank&&c.suit===selected.suit};
app.innerHTML=`<main class="wood"><section class="game"><aside class="players">${g.players.map(p=>`<div class="player ${g.turn===p.id?'active':''}" style="--c:${p.color}"><span class="dot"></span><strong>${p.avatar||'🦊'} ${esc(p.name)}</strong>${p.handCount} cards · ${p.sequences} sequence${p.sequences===1?'':'s'}${g.turn===p.id?'<div class="note">CURRENT TURN</div>':''}</div>`).join('')}</aside><div class="center"><div class="turn">${mine?'YOUR TURN':`CURRENT TURN · ${esc(g.players.find(p=>p.id===g.turn)?.name||'')}`}${selected?` · ${selected.eye==='two'?'WILD — choose any space':selected.eye==='one'?'REMOVE OPPONENT CHIP':'CARD SELECTED'}`:''}</div><div class="board">${g.board.map(c=>`<div class="cell ${c.corner?'free':''} ${legal(c)?'legal':''} ${c.locked.length?'locked':''}" onclick="cell(${c.x},${c.y})">${c.chip?`<i class="chip" style="--c:${g.players.find(p=>p.id===c.chip)?.color}"></i>`:c.label||''}</div>`).join('')}</div></div><aside class="side"><div><div class="eyebrow">DRAW DECK</div><div class="stack"></div><div>${g.deckCount} cards remaining</div></div><div><div class="eyebrow">DISCARD PILE</div><div class="stack discard">${g.discard?.label||'—'}</div></div><div class="history"><div class="eyebrow">MOVE HISTORY</div>${g.history.map(h=>`<p>${esc(h.text)}</p>`).join('')}</div></aside><div class="hand-area"><div class="hand">${me.hand.map(c=>`<button class="card ${['♥','♦'].includes(c.suit)?'red':''} ${state.selected===c.id?'selected':''}" onclick="select('${c.id}')" ${!mine?'disabled':''}><span>${c.label}</span>${c.eye?`<span class="tag">${c.eye==='two'?'WILD JACK':'REMOVE JACK'}</span>`:cardDead(c,g)?'<span class="tag">DEAD CARD</span>':''}<span style="align-self:end">${c.label}</span></button>`).join('')}</div></div></section>${g.winner?`<div class="victory"><section class="panel"><div class="eyebrow">A WINNING LINE</div><h1>SEQUENCE!</h1><p class="subtitle">${esc(g.winner.name)} WINS</p><div class="actions"><button class="btn" onclick="home()">NEW GAME</button><button class="btn dark" onclick="lobby()">RETURN TO LOBBY</button></div></section></div>`:''}</main>`}
function select(cardId){let c=state.game.me.hand.find(x=>x.id===cardId);if(state.selected===cardId){state.selected=null;game();return}state.selected=cardId;game();if(cardDead(c,state.game))toast('Dead card: select it again to discard and draw.');}
async function cell(x,y){let c=state.game.me.hand.find(x=>x.id===state.selected);if(!c)return;if(cardDead(c,state.game)){try{await api('/api/action',{room:state.room,player:state.player,action:{type:'dead',cardId:c.id}});state.selected=null}catch(e){toast(e.message)}return}try{await api('/api/action',{room:state.room,player:state.player,action:{type:'play',cardId:c.id,x,y}});state.selected=null}catch(e){toast(e.message)}}
function howto(){app.innerHTML=`<main class="wood"><section class="setup panel"><div class="eyebrow">HOW TO PLAY</div><h2 class="subtitle">Build five. Think ahead.</h2><div class="seats"><div class="seat" style="--c:#d5aa54"><strong>OBJECTIVE</strong> Make five connected chips across, down, or diagonally. Corners are free wild spaces.</div><div class="seat" style="--c:#d5aa54"><strong>TURNS</strong> Play a card, then place a chip on either matching space. Draw happens automatically.</div><div class="seat" style="--c:#d5aa54"><strong>JACKS</strong> Two-eyed Jacks place anywhere empty. One-eyed Jacks remove an unprotected opponent chip.</div><div class="seat" style="--c:#d5aa54"><strong>DEAD CARDS</strong> If both matching spaces are occupied, exchange the card once per turn, then take your turn.</div><div class="seat" style="--c:#d5aa54"><strong>WINNING</strong> Two players/teams need two sequences; three or four individual players need one.</div></div><button class="btn" onclick="home()">GOT IT</button></section></main>`}
const roomParam=new URLSearchParams(location.search).get('room');if(roomParam){join();setTimeout(()=>document.querySelector('#code').value=roomParam,0)}else home();
